version: '3.9'

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
    depends_on:
      - mysql
      - rabbitmq

  user_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: bucket
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  mysql-data: {}